language: generic

addons:
  apt:
    packages:
    - libunwind8
    - libunwind8-dev
    - gettext
    - libicu-dev
    - liblttng-ust-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - uuid-dev
    - unzip
    - zlib1g
    - zlib1g-dev 
    - libpcre3-dev 
    - libxslt1-dev 
    - libxml2-dev 
    - libgd2-xpm-dev 
    - libgeoip-dev 
    - libsnappy1 
    - libsnappy-dev
  hosts:
  - kafkalocal

env:
  - VERSION: 1.0.$TRAVIS_BUILD_NUMBER
os: linux
dist: trusty
sudo: required

language: csharp
solution: KafkaClient.sln
mono: none
dotnet: 2.0.0

services:
  - docker

before_install:
  # - docker run -d --name zookeeper --publish 2181:2181 zookeeper:3.4
  # - docker run -d --name kafka10_1 --publish 9092:9092 --env ZOOKEEPER_IP=zookeeper --env  KAFKA_BROKER_ID=0 --env KAFKA_DELETE_TOPIC_ENABLE=true --env KAFKA_ADVERTISED_HOST_NAME=kafkalocal ches/kafka:0.10.1.1
  # - docker ps
  - dotnet test -c %CONFIGURATION% -f netcoreapp2.0 src\KafkaClient.Tests\KafkaClient.Tests.csproj --filter "(TestCategory=CI) & (TestCategory!=Flaky)" --logger:trx;LogFileName=test-results.xml;format=AppVeyor

# before_install:
#   # set up the apt-get feed
#   - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
#   - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
#   - sudo apt-get update
#   # Install .NET CLI
#   - sudo apt-get install dotnet-dev-1.0.1

install:
  - dotnet restore -v Minimal

script:
  - dotnet build -c Release -f netstandard1.6 src/KafkaClient/KafkaClient.csproj --no-dependencies --no-incremental
  - dotnet test -c Release -f netcoreapp2.0 src/KafkaClient.Tests/KafkaClient.Tests.csproj --filter "(TestCategory=CI) & (TestCategory!=Flaky)"
  # - dotnet test -c Release -f netcoreapp2.0 src/KafkaClient.Tests/KafkaClient.Tests.csproj --filter "(TestCategory=CI | TestCategory=Integration) & (TestCategory!=Flaky)"

after_success:
  - dotnet pack -c Release -f netcoreapp2.0 src/KafkaClient/KafkaClient.csproj -o artifacts 

