language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
  hosts:
    - kafka1: 40.112.218.47

os: linux
dist: trusty
sudo: required
env: 
  - VERSION=beta

before_install:
  # Install .NET CLI
  - export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129";
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - mkdir $DOTNET_INSTALL_DIR
  - curl -L $DOTNET_SDK_URL -o dotnet_package
  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR

  # Add dotnet to PATH
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

install:
  - dotnet restore -v Minimal

script:
  - dotnet build -c Release -f netstandard1.3 src/KafkaClient --no-dependencies --no-incremental --version-suffix $VERSION
  - dotnet test -c Release src/KafkaClient.Tests --where "cat != Load"

after_success:
  - dotnet pack -c Release src/KafkaClient --version-suffix $VERSION -o artifacts 

