language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - libsnappy1 
    - libsnappy-dev
  hosts:
    - kafka1: 40.112.218.47

os: linux
dist: trusty
sudo: required
env: 
  - VERSION=beta

before_install:
  # set up the apt-get feed
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  # Install .NET CLI
  - sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177

install:
  - dotnet restore -v Minimal

script:
  - dotnet build -c Release -f netstandard1.6 src/KafkaClient --no-dependencies --no-incremental --version-suffix $VERSION
  - dotnet test -c Release src/KafkaClient.Tests --test=KafkaClient.Tests.Unit

after_success:
  - dotnet pack -c Release src/KafkaClient --version-suffix $VERSION -o artifacts 

