language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - libsnappy1 
    - libsnappy-dev

os: linux
dist: trusty
sudo: required

language: csharp
solution: KafkaClient.sln
mono: none
dotnet: 1.0.1

before_install:
  # set up the apt-get feed
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  # Install .NET CLI
  - sudo apt-get install dotnet-dev-1.0.1

install:
  - dotnet restore -v Minimal
  # - nuget restore solution-name.sln
  # - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner 

script:
  - dotnet build -c Release -f netstandard1.6 src/KafkaClient/KafkaClient.csproj --no-dependencies --no-incremental --version-suffix $VERSION
  - dotnet test -c Release -f netcoreapp1.0 src/KafkaClient.Tests/KafkaClient.Tests.csproj --filter "FullyQualifiedName~KafkaClient.Tests.Unit"

after_success:
  - dotnet pack -c Release -f netcoreapp1.0 src/KafkaClient/KafkaClient.csproj --version-suffix $VERSION -o artifacts 

