version: 0.2.{build}

# branches / commits to build
skip_commits:
  message: /WIP/

skip_branch_with_pr: true

# environment
image: Visual Studio 2015

hosts:
  kafka1: 40.112.218.47

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

# built-in goodness
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - cmd: appveyor-retry dotnet restore -v Minimal
  - cmd: dotnet build -c Release src\KafkaClient --no-dependencies --no-incremental --version-suffix %APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack -c Release src\KafkaClient --version-suffix beta -o artifacts 

test_script:
  - cmd: dotnet test -c Release src/KafkaClient.Tests --test=KafkaClient.Tests.Unit --noheader --result=nunit3-unit.xml;format=nunit3
  - ps: $(New-Object "System.Net.WebClient").UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit3-unit.xml))
  - cmd: dotnet test -c Release src/KafkaClient.Tests --test=KafkaClient.Tests.Integration --noheader --result=nunit3-integration.xml;format=nunit3
  - ps: $(New-Object "System.Net.WebClient").UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nunit3-integration.xml))

artifacts:
  - path: artifacts\**\*.*

