version: 1.0.{build}
os: Visual Studio 2015

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release src\KafkaClient --no-dependencies --no-incremental
  - cmd: dotnet build -c Release src\KafkaClient.Tests --no-dependencies --no-incremental

test_script:
  - cmd: dotnet test src\KafkaClient.Tests

notifications:
- provider: Email
  to: awrobins@gmail.com
  on_build_failure: true
  on_build_status_changed: true
