version: 0.2.{build}

# branches / commits to build
skip_commits:
  message: /WIP/

skip_branch_with_pr: true
skip_tags: true

# environment
image: Visual Studio 2017

cache:
  - packages
  
configuration: Release

os: Visual Studio 2017

before_build:
  - dotnet --info
  - dotnet restore  

build:
  parallel: true
  project: KafkaClient.sln

after_build:
# build_script:
#   - cmd: appveyor-retry dotnet restore -v Minimal
#   - cmd: dotnet build -c Release src\KafkaClient\KafkaClient.csproj --no-dependencies --no-incremental --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src\KafkaClient\KafkaClient.csproj --version-suffix beta -o artifacts 

test_script:
  - cmd: dotnet test -c Release -f netcoreapp1.0 src\KafkaClient.Tests\KafkaClient.Tests.csproj --filter "FullyQualifiedName~KafkaClient.Tests.Unit" --logger:trx;LogFileName=tests-results.xml
  # - ps: $wc = New-Object 'System.Net.WebClient'; $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./tests-results.xml))
  # - cmd: dotnet test -c Release src/KafkaClient.Tests --test=KafkaClient.Tests.Integration --noheader --result=nunit3-integration.xml;format=nunit3
  # - ps: $wc = New-Object 'System.Net.WebClient'; $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./nunit3-integration.xml))

artifacts:
  - path: artifacts\**\*.*

