version: 0.2.{build}
skip_branch_with_pr: true
os: Visual Studio 2015
configuration: Release
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - cmd: appveyor-retry dotnet restore -v Minimal

build_script:
  - cmd: dotnet build -c %CONFIGURATION% src\KafkaClient --no-dependencies --no-incremental --version-suffix %APPVEYOR_BUILD_NUMBER%

test_script:
  - cmd: dotnet test -c %CONFIGURATION% src\KafkaClient.Tests --where "cat != Load"

after_build:
  - cmd: dotnet pack -c %CONFIGURATION% src\KafkaClient --version-suffix beta -o artifacts 

artifacts:
- path: artifacts\**\*.*

notifications:
- provider: Email
  to: awrobins@gmail.com
  on_build_failure: true
  on_build_status_changed: true
