version: 0.1.{build}
os: Visual Studio 2015

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release src\KafkaClient --no-dependencies --no-incremental

after_build:
  - cmd: nuget pack src\KafkaClient\KafkaClient.nuspec -Properties "version=%APPVEYOR_BUILD_VERSION%"
 
test_script:
  - cmd: dotnet test src\KafkaClient.Tests --where "cat != Load"

notifications:
- provider: Email
  to: awrobins@gmail.com
  on_build_failure: true
  on_build_status_changed: true
