version: 0.1.{build}-beta
os: Visual Studio 2015

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release src\KafkaClient --no-dependencies --no-incremental --version-suffix %APPVEYOR_BUILD_NUMBER%

after_build:
  - cmd: nuget pack src\KafkaClient\KafkaClient.nuspec -Properties "version=%APPVEYOR_BUILD_VERSION%" -outputdirectory artifacts
 
# test_script:
#   - cmd: dotnet test src\KafkaClient.Tests --where "cat != Load"

artifacts:
- path: artifacts\**\*.*

notifications:
- provider: Email
  to: awrobins@gmail.com
  on_build_failure: true
  on_build_status_changed: true
